language: ruby

cache:
  bundler: true

script: bundler exec rake test
bundler_args: --without development --path vendor/bundle

rvm:
  - 2.1.6
  - 2.1.7
  - 2.1.8
  - 2.1.9
  - 2.2.7
  - 2.3.4
  - 2.4.1
