language: ruby

cache:
  bundler: true
  directories:
    - 'spec/fixtures/puppet_controlrepo/.onceover' # Onceover cache

script: bundle exec rake full_tests
bundler_args: --path vendor/bundle

env:
  - PUPPET_VERSION=~>4.0
  - PUPPET_VERSION=~>5.0
  - PUPPET_VERSION=~>6.0

rvm:
  - 2.3.8
  - 2.4.4
  - 2.5.3
